# These coverage percentages meet thresholds present in the code base
# as of 2022-03-27. As the code gets broken out into maintainable modules,
# these thresholds should increase until they are all at 100%.
branches: 70
functions: 80
lines: 85
statements: 85

files:
  - 'test/**/*.test.js'
